### ISSUE TITLE
Thank you for your attribution mate!

### ISSUE THREAD

**Issue by praveenscience** [NOUX-NOVA/dream-walker#30]
Hey Peter,

Praveen here. Thanks for the surprising attribution you made. The output rocks! 👍🏻 Loved your design man. 🙌🏻 You should have put on much effort on completing the website I guess. Sincerely appreciating you from the bottom of my heart man. Let me know if you need any help in terms of HTML, CSS, JavaScript, jQuery, PHP, MySQL and also, don't hesitate to ask me if you need any hosting space! ;)

Cheers,
Prav

**Comment by NOUX-NOVA** [comment]
Hey Prav,

Thank YOU! This project couldn't have been done without your help!

Peter
